services:
  db:
    image: postgres:15-alpine
    container_name: livraria_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: livraria_antiqua
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: livraria_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: livraria_antiqua
      DB_PASS: 1234
    volumes:
      - ./tomcat-logs:/usr/local/tomcat/logs

volumes:
  postgres_data: